name: decibel
description: A podcast app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animations: ^2.0.7
  audio_service: ^0.18.10
  auto_size_text: ^3.0.0
  awesome_snackbar_content: ^0.1.3
  bloc: ^8.1.2
  cloud_firestore: ^4.5.2
  equatable: ^2.0.5
  extended_image: ^8.0.2
  figma_squircle: ^0.5.3
  firebase_analytics: ^10.4.1
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  # flex_color_scheme: ^7.1.2
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dialogs: ^3.0.0
  flutter_downloader: any
  flutter_hooks: ^0.18.6
  flutter_html: any
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: any
  flutter_spinkit: ^5.2.0
  flutter_svg: ^2.0.7
  form_field_validator: ^1.1.0
  fpdart: ^0.5.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^6.5.7
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  hydrated_bloc: ^8.0.0
  injectable: ^2.1.1
  intl: any
  ionicons: ^0.2.2
  json_annotation: ^4.8.0
  just_audio: ^0.9.34
  just_audio_background: ^0.0.1-beta.10
  mp3_info: ^0.2.1
  percent_indicator: ^4.2.3
  permission_handler: ^10.3.0
  podcast_search:
    git:
      url: https://github.com/amugofjava/podcast_search.git
      ref: feature/pc20-tags
  rxdart: ^0.27.7
  scrollable_positioned_list: ^0.3.8
  sembast: ^3.4.9
  shared_preferences: ^2.1.2
  sliver_tools: ^0.2.10
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.11
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

dependency_overrides:
  intl: 0.18.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/logo/
    - assets/illustrations/
