name: decibel
description: A podcast app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animations: ^2.0.7
  auto_size_text: ^3.0.0
  awesome_snackbar_content: ^0.1.3
  bloc: ^8.1.2
  cloud_firestore: ^4.5.2
  equatable: ^2.0.5
  figma_squircle: ^0.5.3
  firebase_analytics: ^10.4.1
  firebase_auth: ^4.4.2
  firebase_core: ^2.10.0
  flex_color_scheme: ^7.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_svg: ^2.0.6
  form_field_validator: ^1.1.0
  fpdart: ^0.5.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  go_router: ^8.1.0
  google_fonts: ^4.0.3
  google_sign_in: ^6.1.0
  hydrated_bloc: ^9.1.1
  injectable: ^2.1.1
  intl: ^0.18.0
  ionicons: ^0.2.2
  json_annotation: ^4.8.0
  rxdart: ^0.27.7
  smooth_page_indicator: ^1.1.0
  uuid: ^3.0.7

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/logo/
    - assets/illustrations/
