// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0puCHs3S72m0pJoqmGxmzPTza9waf0Xc',
    appId: '1:728802428808:web:8fe37049132ae14f315c3d',
    messagingSenderId: '728802428808',
    projectId: 'decibel-app',
    authDomain: 'decibel-app.firebaseapp.com',
    storageBucket: 'decibel-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNhFzue85Ib0MzukyH_LkCtykJ51_hDU',
    appId: '1:728802428808:android:a0359a275c40037d315c3d',
    messagingSenderId: '728802428808',
    projectId: 'decibel-app',
    storageBucket: 'decibel-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-r_yXyoFr3vuxJatr2MrTc6CiXPYaVv4',
    appId: '1:728802428808:ios:405ecb9d338b1525315c3d',
    messagingSenderId: '728802428808',
    projectId: 'decibel-app',
    storageBucket: 'decibel-app.appspot.com',
    iosClientId: '728802428808-jvdc7dg6nkajnartkqe6ijunvl47pjlv.apps.googleusercontent.com',
    iosBundleId: 'com.decibel.org.decibel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-r_yXyoFr3vuxJatr2MrTc6CiXPYaVv4',
    appId: '1:728802428808:ios:405ecb9d338b1525315c3d',
    messagingSenderId: '728802428808',
    projectId: 'decibel-app',
    storageBucket: 'decibel-app.appspot.com',
    iosClientId: '728802428808-jvdc7dg6nkajnartkqe6ijunvl47pjlv.apps.googleusercontent.com',
    iosBundleId: 'com.decibel.org.decibel',
  );
}
